# Generated by Django 6.0.4 on 2026-04-22 12:03

import django.db.models.deletion
import notes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_passkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_id', models.CharField(blank=True, db_index=True, max_length=16, unique=True)),
                ('file', models.ImageField(upload_to=notes.models._image_upload_to)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='notes.note')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
