# Generated by Django 6.0.4 on 2026-09-14 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_noteapitoken_noteapiidempotencyrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='comments_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=80)),
                ('author_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('is_owner', models.BooleanField(default=False)),
                ('body', models.TextField()),
                ('quote', models.TextField(blank=True)),
                ('prefix', models.CharField(blank=True, max_length=64)),
                ('suffix', models.CharField(blank=True, max_length=64)),
                ('start_offset', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='notes.note')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='notes.comment')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
    ]
